spring:
  application:
    name: change-credentials

  datasource:
    url: jdbc:postgresql://localhost:5432/reset_credentials
    username: partners
    password: partners

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port:
    8082
