eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: user-info
          uri: lb://user-info
          predicates:
            - Path=/profile/**
          filters:
            - AuthenticationFilter

        - id: change-credentials
          uri: lb://change-credentials
          predicates:
            - Path=/change/**
          filters:
            - name: CacheRequestBody
              args:
                bodyClass: java.util.LinkedHashMap
            - ResetCredentialsFilter

server:
  port: 8887


