eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
#TODO add retry filters
#- name: Retry
      #    args:
      #      retries: 3
      #      statuses: BAD_GATEWAY, GATEWAY_TIMEOUT
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: user-info
          uri: lb://user-info
          predicates:
            - Path=/profile/**
          filters:
            - AuthenticationFilter

        - id: change-credentials
          uri: lb://change-credentials
          predicates:
            - Path=/change/**
          filters:
            - name: CacheRequestBody
              args:
                bodyClass: java.util.LinkedHashMap
            - AddIdToRequestFilter

        - id: questionnaire-info
          uri: lb://questionnaire-info
          predicates:
            - Path=/questionnaire/**
          filters:
            - AuthenticationFilter

        - id: announcement-info
          uri: lb://announcement-info
          predicates:
            - Path=/announcement/**
          filters:
            - AuthenticationFilter

        - id: categories-of-work-info
          uri: lb://categories-of-work-info
          predicates:
            - Path=/categories/**
          filters:
            - AuthenticationFilter

        - id: agreement-connection-info
          uri: lb://agreement-connection-info
          predicates:
            - Path=/agreement/**
          filters:
            - AuthenticationFilter


        - id: chat-producer-service
          uri: lb://chat-producer-service
          predicates:
            - Path=/event/**
          filters:
            - AuthenticationFilter

        - id: chat-consumer-service
          uri: lb://chat-consumer-service
          predicates:
            - Path=/chat/**
          filters:
            - AuthenticationFilter

        - id: chat-consumer-websocket-service
          uri: lb://chat-consumer-service
          predicates:
            - Path=/ws/**
          filters:
            - name: DisableCorsFilter
            - name: AuthenticationFilter

#logging:
#  level:
#    org.springframework.web.socket: DEBUG
#    org.springframework.cloud.gateway: DEBUG
#    io.netty: DEBUG
server:
  port: 8887


