spring:
  application:
    name: chat-consumer-service

  datasource:
    url: jdbc:postgresql://localhost:5432/chats
    username: partners
    password: partners

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8088
