spring:
  application:
    name: Contractor-info

  datasource:
    url: jdbc:postgresql://localhost:5432/contractor_info
    username: partners
    password: partners

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        default_schema: contractor


server:
  port: 8090
