eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: questionnaire-info

  datasource:
    url: jdbc:postgresql://localhost:5432/contractor_info
    username: partners
    password: partners

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format-sql: true
        search:
          backend:
            type: lucene
            directory.root: ./data/index
            analysis:
              configurer: partners.questionnaireInfo.config.QuestionnaireAnalysisConfigurer
        default_schema: questionnaire

server:
  port: 8084
logging:
  level:
    org:
      hibernate:
        search: DEBUG


