eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: questionnaire-info

  datasource:
    url: jdbc:postgresql://localhost:5432/contractor_info
    username: partners
    password: partners

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format-sql: true





server:
  port: 8084
