spring:
  application:
    name: Categories-of-work-info

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: partners

  datasource:
    url: jdbc:postgresql://localhost:5432/work_categories
    username: partners
    password: partners

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8085


logging:
  level:
    org:
      springframework:
        messaging: DEBUG
        transaction: DEBUG
        web:
          socket: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
