eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: announcement-info

  datasource:
    url: jdbc:postgresql://localhost:5432/customer_info
    username: partners
    password: partners

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        search:
          backend:
            type: lucene
            directory.root: ./data/index
            analysis:
              configurer: partners.announcement_info.config.AnnouncementAnalysisConfigurer
        default_schema: announcement

server:
  port: 8083